### ISSUE TITLE
Edit name - Save/Cancel buttons overlap name labels

### ISSUE THREAD

**Issue by aydun** [vingle/finsburypark#19]
From the main contact summary page, click the name to edit it:
![Screenshot from 2021-03-10 17-21-52](https://user-images.githubusercontent.com/2730045/110670351-36088300-81c5-11eb-8b39-16073ba23cfd.png)

On Drupal 7.78, Adminimal 7.x-1.26, Civi 5.35.0, Fpark master (v0.11)

**Comment by vingle** [comment]
Thanks - this is the most recurring css bug in the whole theme.. when I fix this I break button positioning elsewhere, and when I fix that I break this (and it works differently between CMSs).

Can you confirm the cms, civi version and fpark version? It might be that this is a case for raising an issue against there being two many ways to layout buttons in civi. Previously I had overrides for each CMS just for this but removed them in the recent Fpark.

**Comment by vingle** [comment]
Should be fixed with latest master. 

I actually was mistaken in my reply because I thought I'd already committed the fix for this I just merged already - but it was still sitting on one site. So actually it's not the serious css bug I claim it was (it would be if it happened again after this fix - but I don't think it will!)

**Comment by aydun** [comment]
Yes, that's fixed it - thanks.

**Comment by vingle** [comment]
It's back: https://lab.civicrm.org/extensions/finsburypark/-/issues/7
